site_name: "template_api"
nav: # on définit l'architecture de la doc en faisant les liens vers les fichiers dans docs
  - Accueil: index.md
  - Documentation:
      - Introduction: api/introduction.md
      - API:
          - main: api/main.md
          - database: api/database.md
          - models: api/models.md
          - crud: api/crud.md
          - auth: api/auth.md
          - router:
            - user_router: api/router/user_router.md
            - data_router: api/router/data_router.md
          - tests:
            - test_database: api/tests/test_database.md

theme:
  name: readthedocs #on peut utiliser d'autre theme de doc

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            rendering:
              show_source: true

# Configuration de déploiement pour GitHub Pages
site_url: https://StevenDelval.github.io/template_api/
repo_url: https://github.com/StevenDelval/template_api