site_name: "template_api"
nav: # on définit l'architecture de la doc en faisant les liens vers les fichiers dans docs
  - Accueil: index.md
  - Documentation:
      - Introduction: api/introduction.md
      - API:
          - crud: api/crud.md

theme:
  name: readthedocs #on peut utiliser d'autre theme de doc

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            rendering:
              show_source: true

# Configuration de déploiement pour GitHub Pages
site_url: https://StevenDelval.github.io/template_api/
repo_url: https://github.com/StevenDelval/template_api